apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: lbd6bt78p-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:63a5d4fb124de3f0801e9a8198ab0ea6eeb419bd@sha256:206be5910675a0d1ce4f2bb21506417f61c0d4e05c133163b0f14a0b5950a7de
          name: container-image
